// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedLibrary.Data;

#nullable disable

namespace SeedLibrary.Migrations
{
    [DbContext(typeof(SeedContext))]
    partial class SeedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SeedLibrary.Models.CommonName", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("CommonName", (string)null);
                });

            modelBuilder.Entity("SeedLibrary.Models.Donation", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SourceId", "SeedId", "Year");

                    b.HasIndex("SeedId");

                    b.ToTable("Donation", (string)null);
                });

            modelBuilder.Entity("SeedLibrary.Models.Growing", b =>
                {
                    b.Property<int>("PlantingDatesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlantingDatesId", "SeedId");

                    b.HasIndex("SeedId");

                    b.ToTable("Growing", (string)null);
                });

            modelBuilder.Entity("SeedLibrary.Models.PlantingDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlantingDate", (string)null);
                });

            modelBuilder.Entity("SeedLibrary.Models.SeedPacket", b =>
                {
                    b.Property<int>("SeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarietyName")
                        .HasColumnType("TEXT");

                    b.HasKey("SeedId");

                    b.HasIndex("VarietyName");

                    b.ToTable("SeedPacket", (string)null);
                });

            modelBuilder.Entity("SeedLibrary.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Source", (string)null);
                });

            modelBuilder.Entity("SeedLibrary.Models.Variety", b =>
                {
                    b.Property<string>("VarietyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonNameName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Depth")
                        .HasColumnType("TEXT");

                    b.HasKey("VarietyName");

                    b.HasIndex("CommonNameName");

                    b.ToTable("Variety", (string)null);
                });

            modelBuilder.Entity("SeedLibrary.Models.Donation", b =>
                {
                    b.HasOne("SeedLibrary.Models.SeedPacket", "SeedPacket")
                        .WithMany("Donations")
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeedLibrary.Models.Source", "Source")
                        .WithMany("Donations")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeedPacket");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SeedLibrary.Models.Growing", b =>
                {
                    b.HasOne("SeedLibrary.Models.PlantingDate", "PlantingDate")
                        .WithMany("Growings")
                        .HasForeignKey("PlantingDatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeedLibrary.Models.SeedPacket", "SeedPacket")
                        .WithMany("Growings")
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantingDate");

                    b.Navigation("SeedPacket");
                });

            modelBuilder.Entity("SeedLibrary.Models.SeedPacket", b =>
                {
                    b.HasOne("SeedLibrary.Models.Variety", "Variety")
                        .WithMany("SeedPackets")
                        .HasForeignKey("VarietyName");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("SeedLibrary.Models.Variety", b =>
                {
                    b.HasOne("SeedLibrary.Models.CommonName", "CommonName")
                        .WithMany("Varieties")
                        .HasForeignKey("CommonNameName");

                    b.Navigation("CommonName");
                });

            modelBuilder.Entity("SeedLibrary.Models.CommonName", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("SeedLibrary.Models.PlantingDate", b =>
                {
                    b.Navigation("Growings");
                });

            modelBuilder.Entity("SeedLibrary.Models.SeedPacket", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Growings");
                });

            modelBuilder.Entity("SeedLibrary.Models.Source", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("SeedLibrary.Models.Variety", b =>
                {
                    b.Navigation("SeedPackets");
                });
#pragma warning restore 612, 618
        }
    }
}
